name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.x"

      - name: Update cmake
        if: matrix.os != 'macos-latest'
        run: |
          pip install cmake
          cmake --version

      - name: Setup environment
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew upgrade cmake
          cmake --version

      - name: Installing codesign certificates
        if: matrix.os == 'macos-latest'
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.APPLE_CERT_DATA }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      - name: Install dependencies (x64)
        run: |
          npm -g i cmake-js
          cd backend/
          npm install
          cmake-js compile -B Release -a x64
          node custom_build.mjs
          npm pack
          cd ..
          npm install ./backend/trackaudio-afv-1.0.0.tgz
          npm install

      - name: Package app
        run: npm run make -- --arch x64

      - name: Install dependencies (arm64)
        if: matrix.os == 'macos-latest'
        run: |
          rm -rf ./backend/build
          rm -rf ./backend/trackaudio-afv-1.0.0.tgz
          cd backend/
          npm install
          cmake-js compile -B Release -a arm64
          node custom_build.mjs
          npm pack
          cd ..
          npm install ./backend/trackaudio-afv-1.0.0.tgz

      - name: Package app
        if: matrix.os == 'macos-latest'
        run: npm run make -- --arch arm64
    
      - name: Codesign on macos
        if: matrix.os == 'macos-latest'
        run: |
          dmg_files=$(find "out/make/" -type f -name "*.dmg")
          for dmg_file in $dmg_files; do
              echo "Codesigning $dmg_file"
              codesign --deep --force --verbose --sign "Developer ID Application" "$dmg_file"
          done

      - id: relinfo
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: pierr3/TrackAudio
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'windows-2019'
        with:
          tag_name: ${{ steps.relinfo.outputs.release }}
          files: "out/make/**/*.zip"

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'macos-latest'
        with:
          tag_name: ${{ steps.relinfo.outputs.release }}
          files: "out/make/**/*.dmg"

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          tag_name: ${{ steps.relinfo.outputs.release }}
          files: "out/make/**/*.deb"
